# CS 486: Machine Learning - Clip It Chat! - Team Hackermans

## Pre-Processing Data

### Importing Packages

In [14]:
import pandas as pd
import numpy as np

### Reading CSV Files

In [15]:
df = pd.read_csv("combined_csv.csv")

df.drop("Unnamed: 0", inplace = True, axis = 1)
df.drop("created_at", inplace = True, axis = 1)

df

body  scores
0      lived through a heart attack SeemsGood     0.0
1                          @junior90007 amaz3     0.0
2                                          D:     0.5
3         rooBlind rooBlind rooBlind rooBlind     0.0
4                                          66     0.0
...                                       ...     ...
50994                                    LULW     1.0
50995                                DansGame     0.7
50996                                       1     0.0
50997                                     LOL     1.0
50998                                  monkaW     0.7

[50999 rows x 2 columns]

### Splitting Up Dataset

In [16]:
train_x = df.iloc[:, 0]
train_y = df.iloc[:, 1]

In [17]:
train_x

0        lived through a heart attack SeemsGood
1                            @junior90007 amaz3
2                                            D:
3           rooBlind rooBlind rooBlind rooBlind
4                                            66
                          ...                  
50994                                      LULW
50995                                  DansGame
50996                                         1
50997                                       LOL
50998                                    monkaW
Name: body, Length: 50999, dtype: object

In [18]:
train_y

0        0.0
1        0.0
2        0.5
3        0.0
4        0.0
        ... 
50994    1.0
50995    0.7
50996    0.0
50997    1.0
50998    0.7
Name: scores, Length: 50999, dtype: float64

### Encoding Text Data

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
x_train_counts = count_vect.fit_transform(train_x).toarray()

In [20]:
x_train_counts.shape

(50999, 26477)

### Assigning Clip-Worthy Metric

In [21]:
df.loc[df["scores"] >= .5, "Clip Worthy Message"] = "Hype"
df.loc[df["scores"] < .5, "Clip Worthy Message"] = "Not Hype"

df

body  scores Clip Worthy Message
0      lived through a heart attack SeemsGood     0.0            Not Hype
1                          @junior90007 amaz3     0.0            Not Hype
2                                          D:     0.5                Hype
3         rooBlind rooBlind rooBlind rooBlind     0.0            Not Hype
4                                          66     0.0            Not Hype
...                                       ...     ...                 ...
50994                                    LULW     1.0                Hype
50995                                DansGame     0.7                Hype
50996                                       1     0.0            Not Hype
50997                                     LOL     1.0                Hype
50998                                  monkaW     0.7                Hype

[50999 rows x 3 columns]

In [22]:
train_z = df.iloc[:, 2]

train_z

0        Not Hype
1        Not Hype
2            Hype
3        Not Hype
4        Not Hype
           ...   
50994        Hype
50995        Hype
50996    Not Hype
50997        Hype
50998        Hype
Name: Clip Worthy Message, Length: 50999, dtype: object

## Encoding Labels and Fitting Data

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(train_z)
train_z = le.transform(train_z)

train_z

array([1, 1, 0, ..., 1, 0, 0])

## Running Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(x_train_counts, train_z)

C:\Users\omar_\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## Pre-Processing Test Data

In [25]:
df = pd.read_csv("scored/tsm_myth.csv")

df.drop("Unnamed: 0", inplace = True, axis = 1)
df.drop("created_at", inplace = True, axis = 1)

test_x = df.iloc[:, 0]
test_y = df.iloc[:, 1]

### Assigning Clip-Worthy Metric

In [26]:
df.loc[df["scores"] >= .5, "Clip Worthy Message"] = "Hype"
df.loc[df["scores"] < .5, "Clip Worthy Message"] = "Not Hype"

df

body    scores  \
0                                        put the song!  0.333333   
1                          where did u get that shirt?  0.166667   
2                                         100K100K100K  0.500000   
3               Myth and hamlinz are a really good duo  0.000000   
4                                          BROO CHILLL  0.500000   
..                                                 ...       ...   
995  mthSad mthSad mthSad mthSad mthSad mthSad mthS...  0.000000   
996  Noo don’t do it like this the screen is so bad...  0.000000   
997                          Myth just has godly delts  0.000000   
998                      what game is that????????????  1.000000   
999                                       mthPose mthC  0.000000   

    Clip Worthy Message  
0              Not Hype  
1              Not Hype  
2                  Hype  
3              Not Hype  
4                  Hype  
..                  ...  
995            Not Hype  
996            Not Hype  
997            Not Hype  
998                Hype  
999            Not Hype  

[1000 rows x 3 columns]

In [27]:
test_z = df.iloc[:, 2]

test_z

0      Not Hype
1      Not Hype
2          Hype
3      Not Hype
4          Hype
         ...   
995    Not Hype
996    Not Hype
997    Not Hype
998        Hype
999    Not Hype
Name: Clip Worthy Message, Length: 1000, dtype: object

### Encoding Test Text Data

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
x_test_counts = count_vect.transform(test_x).toarray()

C:\Users\omar_\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\feature_extraction\text.py:1208: UserWarning: Upper case characters found in vocabulary while 'lowercase' is True. These entries will not be matched with any documents
  warnings.warn(


### Fitting Data

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(test_z)
test_z = le.transform(test_z)

## Creating Predictions

In [30]:
hyp = clf.predict(x_test_counts)
hyp

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,

## Generating Accuracy Scores

In [31]:
from sklearn.metrics import accuracy_score

accuracy_score(test_z, hyp)

0.855

## Generating Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix

confusion_matrix(test_z, hyp)

array([[ 90, 126],
       [ 19, 765]], dtype=int64)

## Exporting Model Data

In [33]:
import pickle

pickle.dump(clf, open("output.sav", "wb"))

In [34]:
loaded_model = pickle.load(open("output.sav", "rb"))
loaded_model.predict(x_test_counts)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,